services:
  - type: web
    name: quoteapi
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: TOKEN
        sync: false
      - key: NODE_ENV
        value: production
